"use client";
import {useEffect,useState} from "react";
import {Building2,Car,HeartPulse,House,Menu,Shield,ShoppingCart,Users,X} from "lucide-react";
const API="https://horizonville-backend.onrender.com";
const defaults={heroTitle:"HorizonVille",heroLabel:"SUA HISTÓRIA COMEÇA AQUI",heroSubtitle:"Mais que um servidor, uma cidade viva. Escolha seu caminho e escreva sua história no MTA.",heroButton:"ENTRAR NA CIDADE",discordUrl:"https://discord.gg/CeV8m7hxFD",heroImage:"/city-night.png",aboutTitle:"Explore nossa cidade",aboutText:"Uma metrópole construída para histórias marcantes, sistemas modernos e uma comunidade que transforma cada escolha em uma nova experiência.",whitelistTitle:"Sua jornada começa na Whitelist",whitelistText:"Entre no Discord, conheça as regras e mostre que está preparado para viver uma nova história.",paths:["Polícia","SAMU","Empresas","Empregos civis","Organizações","Vida urbana"]};
type Content=typeof defaults;
export default function SiteClient(){const[c,setC]=useState<Content>(defaults),[menu,setMenu]=useState(false),[user,setUser]=useState<any>(null);useEffect(()=>{fetch("/api/content").then(r=>r.ok?r.json():null).then(x=>x&&setC({...defaults,...x})).catch(()=>{});const q=new URLSearchParams(location.search),token=q.get("token")||q.get("auth_token");if(token){localStorage.setItem("hv_user_token",token);history.replaceState({},"","/")}const t=token||localStorage.getItem("hv_user_token");if(t)fetch(API+"/api/account/me",{headers:{Authorization:"Bearer "+t}}).then(r=>r.ok?r.json():null).then(setUser).catch(()=>{})},[]);const login=()=>location.href=API+"/api/auth/discord/start?returnTo="+encodeURIComponent(location.origin+"/");return <main>
<header className="nav-shell"><a className="brand" href="#inicio"><img src="/hv-logo.png" alt="HV"/><span>HORIZONVILLE<small>ROLEPLAY</small></span></a><nav className={menu?"open":""}><a href="#inicio">INÍCIO</a><a href="#cidade">CIDADE</a><a href="#como-jogar">COMO JOGAR</a><a href="#loja">LOJA</a></nav><div className="nav-actions">{user?<button className="account"><img src={user.user?.avatar} alt=""/><span>{user.user?.displayName||user.user?.username}</span></button>:<button className="account" onClick={login}><Users size={18}/> CONECTAR-SE</button>}<a className="cart" href="#loja"><ShoppingCart/><b>0</b></a><button className="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<section id="inicio" className="hero"><div className="hero-copy"><div className="kicker"><i/>{c.heroLabel}<i/></div><h1>HORIZON<span>VILLE</span></h1><h2>ROLEPLAY</h2><p>{c.heroSubtitle}</p><a className="main-cta" href={c.discordUrl}><Building2/> {c.heroButton}<b>→</b></a><div className="hero-pills"><span><Users/><b>Comunidade</b><small>Ativa e engajada</small></span><span><Building2/><b>Cidade</b><small>Viva e dinâmica</small></span><span><Shield/><b>Roleplay</b><small>Sério e realista</small></span></div></div><div className="hero-portal"><div className="rings"/><img className="city" src={c.heroImage} alt="Cidade HorizonVille"/><img className="hero-logo" src="/hv-logo.png" alt="Logo HV"/><span className="online">● SERVIDOR ONLINE</span></div><a className="scroll" href="#cidade">⌄</a></section>
<section id="cidade" className="section city-section"><div className="section-title"><small>EXPLORE</small><h2>{c.aboutTitle}</h2><p>{c.aboutText}</p></div><div className="path-grid">{c.paths.map((p,i)=>{const Icon=[Shield,HeartPulse,Building2,Car,Users,House][i]||Building2;return <article key={p}><span>0{i+1}</span><Icon/><h3>{p}</h3><p>Construa sua trajetória com sistemas próprios e novas possibilidades todos os dias.</p></article>})}</div></section>
<section id="como-jogar" className="section whitelist"><div><small>COMECE AGORA</small><h2>{c.whitelistTitle}</h2><p>{c.whitelistText}</p></div><ol><li><b>01</b><span>Conecte seu Discord</span></li><li><b>02</b><span>Leia as regras</span></li><li><b>03</b><span>Faça a Whitelist</span></li><li><b>04</b><span>Entre na cidade</span></li></ol></section>
<section id="loja" className="section store-call"><div><small>MARKETPLACE</small><h2>Leve sua experiência além</h2><p>VIPs, veículos e vantagens para personalizar sua história.</p></div><a className="main-cta" href="/loja"><ShoppingCart/> EXPLORAR A LOJA <b>→</b></a></section>
<footer><img src="/hv-logo.png" alt="HV"/><div><b>HorizonVille Roleplay</b><span>Uma cidade feita para histórias reais.</span></div><p>© 2026 HorizonVille Roleplay</p></footer></main>}
